import Link from "next/link";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata = { title: "About — YuE2 Music Studio" };

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-5">
      <h1 className="text-xl font-semibold tracking-tight">About and licensing</h1>

      <Card>
        <CardHeader>
          <CardTitle>Model weights</CardTitle>
          <CardDescription>Checkpoint licensing is separate from this application&apos;s source.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 text-sm leading-relaxed text-[var(--color-ink-muted)]">
          <p>
            Music is generated by <strong className="text-[var(--color-ink)]">m-a-p/YuE2-3B</strong> and decoded by{" "}
            <strong className="text-[var(--color-ink)]">m-a-p/YuE2-Vae</strong>. The current checkpoint weights are
            licensed <strong className="text-[var(--color-ink)]">CC BY-NC 4.0</strong> — non-commercial use, with
            attribution.
          </p>
          <p>
            That licence covers the weights, not this application. Nothing here grants unrestricted commercial rights
            to the audio those weights produce. Check the licence text shipped alongside the weights in your models
            directory before you distribute anything.
          </p>
          <p>
            The YuE2 runtime (<code className="font-mono">yue2-infer</code>) and the YuE repository are Apache-2.0.
            The ABC parser used for score validation is vendored from that repository under the same licence, with
            its notice preserved in{" "}
            <code className="font-mono">packages/core/yue2_studio_core/vendor/</code>.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>What this application is</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm leading-relaxed text-[var(--color-ink-muted)]">
          <p>
            A local-first studio around the open YuE2 runtime. Generation runs on this machine&apos;s GPU; nothing is
            sent anywhere. Projects, audio, scores and manifests live in the data directory as ordinary files.
          </p>
          <p>
            The interaction model — a create screen, song cards, a queue, a library — is inspired by modern music
            tools. No proprietary code, assets or branding from any of them is used here.
          </p>
          <p>
            See <Link href="/system" className="text-[var(--color-accent)] hover:underline">System</Link> for the
            runtime versions and capabilities this installation actually has.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
